product-os/jellyfish-plugin-product-os

- lib/cards/triggered-action-merge-draft-version.ts
Signed-off-by: Martin Rauscher <martin@balena.io>
> don't merge non-ready contracts

- lib/cards/view-all-types.ts
Change-type: minor
Signed-off-by: Martin Rauscher <martin@balena.io>
> add types view

- lib/cards/index.ts
- lib/cards/view-all-types.ts
Signed-off-by: Martin Rauscher <martin@balena.io>
> add missing index entry for types view

- lib/cards/view-all-types.ts
Signed-off-by: Martin Rauscher <martin@balena.io>
> fix types view name

- package.json
Signed-off-by: Carol Schulze <carol@balena.io>
> Remove dev-only peer dependency

- lib/index.ts
> Remove main plugin argument

- lib/index.ts
> Use package.json version as plugin version

- package.json
> Update to worker 18

- package.json
> Update skhema from 6.0.3 to 6.0.6

- package.json
> Update @balena/jellyfish-worker from 19.0.23 to 20.0.0

- package.json
- repo.yml
- scripts/generate-contract-interfaces.js
Signed-off-by: Lucian Buzzo <lucian.buzzo@gmail.com>
> Use autumndb instead of jellyfish-core

- package.json
> Bump worker and autumndb

- lib/contracts/index.ts
- lib/index.ts
- package.json
> Update @balena/jellyfish-worker from 20.2.0 to 21.0.0

- package.json
> Update @balena/jellyfish-worker from 21.0.0 to 21.2.0

- package.json
> Update @balena/jellyfish-worker from 21.2.0 to 22.0.0

- package.json
> Update @balena/jellyfish-worker from 22.1.13 to 23.0.0

- lib/contracts/index.ts
- lib/contracts/relationship-contract-repository-contains-any.ts
- lib/contracts/relationship-contract-repository-latest-any.ts
- lib/contracts/relationship-loop-owns-contract-repository.ts
- tsconfig.json
Add relationships defined between contract types in the module, or between contract types in the module and its dependencies
Signed-off-by: Ramiro Gonzalez <ramiro.gonzalez@balena.io>
> Add relationship definitions

- package.json
> Update worker to v25

- package.json
> Update worker to v26

- package.json
> Update @balena/jellyfish-worker from 28.0.6 to 29.0.0

- package.json
> Update @balena/jellyfish-worker from 30.0.7 to 30.0.13

- lib/contracts/contract-repository.ts
- lib/contracts/index.ts
- lib/contracts/loop-balena-io.ts
- lib/contracts/loop-balenalabs.ts
- lib/contracts/loop-company-os.ts
- lib/contracts/loop-product-os.ts
- lib/contracts/loop-team-os.ts
- lib/contracts/role-loop.ts
- lib/contracts/view-all-jellyfish-support-threads.ts
- package.json
> Drop @balena/jellyfish-types

- package.json
> Update jellyfish-worker to v31
